const fs = require('fs');
const issues = [
  {"ID": 2350899, "Comp": "Input + Dropdown", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/input + atoms/dropdown"},
  {"ID": 2350901, "Comp": "Input + Dropdown", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "atoms/input + atoms/dropdown"},
  {"ID": 2350975, "Comp": "Calendar (month/year header)", "Sum": "Function cannot be performed by keyboard alone", "WCAG": "2.1.1", "Path": "organisms/calendar"},
  {"ID": 2350976, "Comp": "Calendar (month/year header)", "Sum": "Button: Button does not have a role", "WCAG": "4.1.2", "Path": "organisms/calendar"},
  {"ID": 2350978, "Comp": "Calendar (date cells)", "Sum": "Function cannot be performed by keyboard alone", "WCAG": "2.1.1", "Path": "organisms/calendar"},
  {"ID": 2350980, "Comp": "Calendar", "Sum": "Grid: Grid is missing appropriate roles and/or attributes", "WCAG": "4.1.2", "Path": "organisms/calendar"},
  {"ID": 2351000, "Comp": "Calendar (date cells)", "Sum": "State: Selected state of the element is missing or incorrect", "WCAG": "4.1.2", "Path": "organisms/calendar"},
  {"ID": 2351011, "Comp": "Button (Calendar navigation)", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/button"},
  {"ID": 2351265, "Comp": "Dropdown (Option)", "Sum": "Focus indicator is missing", "WCAG": "2.4.7", "Path": "atoms/dropdown/option"},
  {"ID": 2351299, "Comp": "Dropdown", "Sum": "Select: Custom select does not have a role and/or state", "WCAG": "4.1.2", "Path": "atoms/dropdown"},
  {"ID": 2351366, "Comp": "Input (DatePicker trigger)", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/input"},
  {"ID": 2351367, "Comp": "Input (DatePicker trigger)", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "atoms/input"},
  {"ID": 2352169, "Comp": "Icon", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/icon"},
  {"ID": 2353856, "Comp": "Input", "Sum": "Controls have same name but different actions", "WCAG": "2.4.6", "Path": "atoms/input"},
  {"ID": 2353857, "Comp": "Input", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "atoms/input"},
  {"ID": 2353858, "Comp": "Text (password requirements list)", "Sum": "Visual list is not marked up as list", "WCAG": "1.3.1", "Path": "atoms/text"},
  {"ID": 2353859, "Comp": "Text (password requirements list)", "Sum": "Role: The element's role is missing or incorrect", "WCAG": "4.1.2", "Path": "atoms/text"},
  {"ID": 2353861, "Comp": "Icon", "Sum": "Text alternative does not present same info as image", "WCAG": "1.1.1", "Path": "atoms/icon"},
  {"ID": 2353862, "Comp": "Icon (visibility toggle in Input)", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/icon"},
  {"ID": 2354325, "Comp": "Input", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/input"},
  {"ID": 2354327, "Comp": "Input", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "atoms/input"},
  {"ID": 2354461, "Comp": "Select", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "organisms/select"},
  {"ID": 2354462, "Comp": "Select", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "organisms/select"},
  {"ID": 2354808, "Comp": "Listbox (in Select)", "Sum": "Focus indicator is missing", "WCAG": "2.4.7", "Path": "organisms/listbox"},
  {"ID": 2354809, "Comp": "Select", "Sum": "Select: Custom select does not have a role and/or state", "WCAG": "4.1.2", "Path": "organisms/select"},
  {"ID": 2354814, "Comp": "Calendar (in Popover)", "Sum": "Focused element is completely covered by other content", "WCAG": "2.4.11", "Path": "organisms/calendar"},
  {"ID": 2354984, "Comp": "Calendar", "Sum": "Grid: Grid is missing appropriate roles and/or attributes", "WCAG": "4.1.2", "Path": "organisms/calendar"},
  {"ID": 2355000, "Comp": "Input (DateRangePicker trigger)", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/input"},
  {"ID": 2355001, "Comp": "Input (DateRangePicker trigger)", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "atoms/input"},
  {"ID": 2355003, "Comp": "Calendar (date cells)", "Sum": "State: Selected state of the element is missing or incorrect", "WCAG": "4.1.2", "Path": "organisms/calendar"},
  {"ID": 2355006, "Comp": "Input (DateRangePicker trigger)", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/input"},
  {"ID": 2355007, "Comp": "Calendar (date cells)", "Sum": "Function cannot be performed by keyboard alone", "WCAG": "2.1.1", "Path": "organisms/calendar"},
  {"ID": 2355038, "Comp": "Calendar (date cells)", "Sum": "State: Selected state of the element is missing or incorrect", "WCAG": "4.1.2", "Path": "organisms/calendar"},
  {"ID": 2355056, "Comp": "Checkbox (in Grid)", "Sum": "Form field: Form field is missing an accessible name", "WCAG": "4.1.2", "Path": "atoms/checkbox"},
  {"ID": 2355060, "Comp": "Checkbox (in Grid)", "Sum": "Accessible name missing", "WCAG": "2.5.3", "Path": "atoms/checkbox"},
  {"ID": 2355412, "Comp": "Grid (Table)", "Sum": "Status message not automatically announced", "WCAG": "4.1.3", "Path": "organisms/grid"},
  {"ID": 2355413, "Comp": "Grid (Table) - Filters panel", "Sum": "Keyboard focus order is not logical", "WCAG": "2.4.3", "Path": "organisms/grid"},
  {"ID": 2355418, "Comp": "Grid (Table) - Filters panel", "Sum": "Correct reading order of dynamic content not determinable", "WCAG": "1.3.2", "Path": "organisms/grid"},
  {"ID": 2355451, "Comp": "Grid (column options Button)", "Sum": "Controls have same name but different actions", "WCAG": "2.4.6", "Path": "organisms/grid"},
  {"ID": 2355452, "Comp": "Grid (column headers)", "Sum": "Function cannot be performed by keyboard alone", "WCAG": "2.1.1", "Path": "organisms/grid"},
  {"ID": 2355453, "Comp": "Grid (column headers)", "Sum": "State: Table sort state is missing or incorrect", "WCAG": "4.1.2", "Path": "organisms/grid"},
  {"ID": 2355469, "Comp": "Input (search)", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/input"},
  {"ID": 2355470, "Comp": "MetricInput (in Pagination)", "Sum": "Form field: Form field is missing an accessible name", "WCAG": "4.1.2", "Path": "molecules/metricInput"},
  {"ID": 2355471, "Comp": "Grid (Table)", "Sum": "Data table has missing or incomplete header cell markup", "WCAG": "1.3.1", "Path": "organisms/grid"},
  {"ID": 2355479, "Comp": "Dropdown (Option)", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/dropdown/option"},
  {"ID": 2355484, "Comp": "Grid (column options Dropdown)", "Sum": "Correct reading order of dynamic content not determinable", "WCAG": "1.3.2", "Path": "organisms/grid"},
  {"ID": 2355494, "Comp": "Label (in filter panel)", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/label"},
  {"ID": 2355495, "Comp": "Label (in filter panel)", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "atoms/label"},
  {"ID": 2355517, "Comp": "Text (status message)", "Sum": "Status message not automatically announced", "WCAG": "4.1.3", "Path": "atoms/text"},
  {"ID": 2355520, "Comp": "Chip (close icon)", "Sum": "Controls have same name but different actions", "WCAG": "2.4.6", "Path": "atoms/chip"},
  {"ID": 2355538, "Comp": "Label", "Sum": "Status message not automatically announced", "WCAG": "4.1.3", "Path": "atoms/label"},
  {"ID": 2355559, "Comp": "VerificationCodeInput", "Sum": "Form field: Form field is missing an accessible name", "WCAG": "4.1.2", "Path": "molecules/verificationCodeInput"},
  {"ID": 2355560, "Comp": "VerificationCodeInput", "Sum": "Group of form controls not associated with group label", "WCAG": "1.3.1", "Path": "molecules/verificationCodeInput"},
  {"ID": 2355561, "Comp": "Text (styled as link - should be Link/Button)", "Sum": "Function cannot be performed by keyboard alone", "WCAG": "2.1.1", "Path": "atoms/text"},
  {"ID": 2355562, "Comp": "Text (styled as link - should be Link/Button)", "Sum": "Button: Button does not have a role", "WCAG": "4.1.2", "Path": "atoms/text"},
  {"ID": 2355563, "Comp": "Text", "Sum": "Visual heading text is not marked as heading", "WCAG": "1.3.1", "Path": "atoms/text"},
  {"ID": 2355626, "Comp": "VerticalNav (MenuItem)", "Sum": "State: Selected state of the element is missing or incorrect", "WCAG": "4.1.2", "Path": "organisms/verticalNav"},
  {"ID": 2355666, "Comp": "HorizontalNav", "Sum": "Focus indicator is missing", "WCAG": "2.4.7", "Path": "organisms/horizontalNav"},
  {"ID": 2355667, "Comp": "HorizontalNav (nested interactive)", "Sum": "Anchor or button nested inside other anchor or button", "WCAG": "4.1.2", "Path": "organisms/horizontalNav"},
  {"ID": 2355808, "Comp": "VerticalNav (collapsed icons)", "Sum": "Focus indicator is missing", "WCAG": "2.4.7", "Path": "organisms/verticalNav"},
  {"ID": 2355810, "Comp": "Icon (in VerticalNav)", "Sum": "Text alternative does not present same info as image", "WCAG": "1.1.1", "Path": "atoms/icon"},
  {"ID": 2355850, "Comp": "VerticalNav (collapsed tooltip)", "Sum": "Additional content not dismissible", "WCAG": "1.4.13", "Path": "organisms/verticalNav"},
  {"ID": 2355851, "Comp": "Collapsible (trigger button)", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/collapsible"},
  {"ID": 2355862, "Comp": "Select (focus management)", "Sum": "Keyboard focus is lost or misplaced due to user interaction or content update", "WCAG": "2.4.3", "Path": "organisms/select"},
  {"ID": 2355895, "Comp": "Input", "Sum": "Identify input purpose not accurate", "WCAG": "1.3.5", "Path": "atoms/input"},
  {"ID": 2355898, "Comp": "Input", "Sum": "Identify input purpose not accurate", "WCAG": "1.3.5", "Path": "atoms/input"},
  {"ID": 2355933, "Comp": "Input", "Sum": "Identify input purpose not accurate", "WCAG": "1.3.5", "Path": "atoms/input"},
  {"ID": 2356021, "Comp": "Input", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/input"},
  {"ID": 2356022, "Comp": "Input", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "atoms/input"},
  {"ID": 2356024, "Comp": "Select", "Sum": "Controls have same name but different actions", "WCAG": "2.4.6", "Path": "organisms/select"},
  {"ID": 2356058, "Comp": "Stepper", "Sum": "State: Selected state of the element is missing or incorrect", "WCAG": "4.1.2", "Path": "molecules/stepper"},
  {"ID": 2356783, "Comp": "Select (trigger)", "Sum": "Controls have same name but different actions", "WCAG": "2.4.6", "Path": "organisms/select"},
  {"ID": 2356784, "Comp": "Select (trigger)", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "organisms/select"},
  {"ID": 2356794, "Comp": "Text", "Sum": "Visual heading text is not marked as heading", "WCAG": "1.3.1", "Path": "atoms/text"},
  {"ID": 2356802, "Comp": "Select", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "organisms/select"},
  {"ID": 2356803, "Comp": "Select + Input", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "organisms/select + atoms/input"},
  {"ID": 2356804, "Comp": "Slider (handle)", "Sum": "Button: Button is missing both a role and a name", "WCAG": "4.1.2", "Path": "organisms/slider"},
  {"ID": 2356805, "Comp": "Slider (handle)", "Sum": "Accessible name missing", "WCAG": "2.5.3", "Path": "organisms/slider"},
  {"ID": 2356806, "Comp": "Slider (handle)", "Sum": "State: Selected state of the element is missing or incorrect", "WCAG": "4.1.2", "Path": "organisms/slider"},
  {"ID": 2356807, "Comp": "Select", "Sum": "State: Selected state of the element is missing or incorrect", "WCAG": "4.1.2", "Path": "organisms/select"},
  {"ID": 2356809, "Comp": "Icon (close - in Select + Input)", "Sum": "Controls have same name but different actions", "WCAG": "2.4.6", "Path": "atoms/icon"},
  {"ID": 2356810, "Comp": "Select (focus management)", "Sum": "Keyboard focus is lost or misplaced due to user interaction or content update", "WCAG": "2.4.3", "Path": "organisms/select"},
  {"ID": 2356813, "Comp": "Listbox (in Select)", "Sum": "Accessible name missing", "WCAG": "2.5.3", "Path": "organisms/listbox"},
  {"ID": 2356816, "Comp": "Select (trigger)", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "organisms/select"},
  {"ID": 2356817, "Comp": "Select (trigger)", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "organisms/select"},
  {"ID": 2356818, "Comp": "Radio", "Sum": "Group of form controls not associated with group label", "WCAG": "1.3.1", "Path": "atoms/radio"},
  {"ID": 2356819, "Comp": "Slider", "Sum": "Action cannot be performed with a screen reader turned on", "WCAG": "2.1.1", "Path": "organisms/slider"},
  {"ID": 2356820, "Comp": "Input", "Sum": "Form field: Form field is missing an accessible name", "WCAG": "4.1.2", "Path": "atoms/input"},
  {"ID": 2356833, "Comp": "Select", "Sum": "Select: Custom select does not have a role and/or state", "WCAG": "4.1.2", "Path": "organisms/select"},
  {"ID": 2356835, "Comp": "Checkbox", "Sum": "Group of form controls not associated with group label", "WCAG": "1.3.1", "Path": "atoms/checkbox"},
  {"ID": 2356836, "Comp": "Button", "Sum": "Controls have same name but different actions", "WCAG": "2.4.6", "Path": "atoms/button"},
  {"ID": 2356837, "Comp": "Select", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "organisms/select"},
  {"ID": 2356838, "Comp": "Radio", "Sum": "Group of form controls not associated with group label", "WCAG": "1.3.1", "Path": "atoms/radio"},
  {"ID": 2356839, "Comp": "Button", "Sum": "Button: Button pressed state is not conveyed", "WCAG": "4.1.2", "Path": "atoms/button"},
  {"ID": 2356840, "Comp": "Select", "Sum": "Select: Custom select does not have a role and/or state", "WCAG": "4.1.2", "Path": "organisms/select"},
  {"ID": 2356843, "Comp": "Input", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/input"},
  {"ID": 2356844, "Comp": "Input", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "atoms/input"},
  {"ID": 2356851, "Comp": "Select (focus management)", "Sum": "Keyboard focus is lost or misplaced due to user interaction or content update", "WCAG": "2.4.3", "Path": "organisms/select"},
  {"ID": 2356853, "Comp": "Input", "Sum": "Identify input purpose not accurate", "WCAG": "1.3.5", "Path": "atoms/input"},
  {"ID": 2356862, "Comp": "Select", "Sum": "Elements must only use supported ARIA attributes", "WCAG": "4.1.2", "Path": "organisms/select"},
  {"ID": 2356866, "Comp": "Select (focus management)", "Sum": "Keyboard focus is lost or misplaced due to user interaction or content update", "WCAG": "2.4.3", "Path": "organisms/select"},
  {"ID": 2356867, "Comp": "Input (DateRangePicker trigger)", "Sum": "Keyboard focus is lost or misplaced due to user interaction or content update", "WCAG": "2.4.3", "Path": "atoms/input"},
  {"ID": 2356869, "Comp": "Select", "Sum": "Select: Custom select does not have a role and/or state", "WCAG": "4.1.2", "Path": "organisms/select"},
  {"ID": 2356870, "Comp": "Listbox (in Select)", "Sum": "Accessible name does not contain visible label", "WCAG": "2.5.3", "Path": "organisms/listbox"},
  {"ID": 2356873, "Comp": "Select (focus management)", "Sum": "Keyboard focus is lost or misplaced due to user interaction or content update", "WCAG": "2.4.3", "Path": "organisms/select"},
  {"ID": 2356875, "Comp": "Select", "Sum": "Select: Custom select does not have a role and/or state", "WCAG": "4.1.2", "Path": "organisms/select"},
  {"ID": 2356879, "Comp": "InputMask", "Sum": "Label is not persistent", "WCAG": "3.3.2", "Path": "molecules/inputMask"},
  {"ID": 2356881, "Comp": "Textarea", "Sum": "Form field: Form field is missing an accessible name", "WCAG": "4.1.2", "Path": "atoms/textarea"},
  {"ID": 2356882, "Comp": "Textarea", "Sum": "Accessible name missing", "WCAG": "2.5.3", "Path": "atoms/textarea"},
  {"ID": 2356883, "Comp": "Switch", "Sum": "Form field: Form field is missing an accessible name", "WCAG": "4.1.2", "Path": "atoms/switchInput"},
  {"ID": 2356884, "Comp": "Switch", "Sum": "Accessible name missing", "WCAG": "2.5.3", "Path": "atoms/switchInput"},
  {"ID": 2356892, "Comp": "Text", "Sum": "Visual heading text is not marked as heading", "WCAG": "1.3.1", "Path": "atoms/text"},
  {"ID": 2358025, "Comp": "Checkbox", "Sum": "Programmatic label does not convey purpose of control", "WCAG": "2.4.6", "Path": "atoms/checkbox"},
  {"ID": 2358043, "Comp": "Input (in Grid)", "Sum": "Visible label missing", "WCAG": "3.3.2", "Path": "atoms/input"},
  {"ID": 2358050, "Comp": "Grid (column resize)", "Sum": "Functionality requires a dragging movement with no alternative", "WCAG": "2.5.7", "Path": "organisms/grid"},
  {"ID": 2358053, "Comp": "Input (in Grid)", "Sum": "Visible label missing", "WCAG": "3.3.2", "Path": "atoms/input"}
];

let md = `# Accessibility Issue Tracker\n\n`;
md += `| # | Component | Issue Summary | WCAG Criterion | Suggested Fix | Status | Notes |\n`;
md += `|---|-----------|--------------|----------------|---------------|--------|-------|\n`;

let count = 1;
for (const issue of issues) {
  md += `| ${count++} | ${issue.Comp} | ${issue.Sum} | ${issue.WCAG} | TBD | [ ] Pending | |\n`;
}

fs.writeFileSync('A11Y_ISSUE_TRACKER.md', md);
console.log('Tracker generated with ' + (count - 1) + ' issues.');
