export default [
  {
    id: 'C1000000017',
    status: 'Enrolled',
    patientList: [
      {
        address: 'New York No. 1 Lake Park',
        name: 'John Brown',
        age: '32y',
        gender: 'Male',
        dob: '01/01/1990',
        status: 'Enrolled',
        referredOn: '01/01/2020',
        program: 'Hepatitis',
      },
      {
        address: 'New York No. 2 Lake Park',
        name: 'Alice Brown',
        age: '30y',
        gender: 'Female',
        dob: '15/03/1992',
        status: 'Completed',
        referredOn: '12/05/2021',
        program: 'Diabetes',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000018',
    status: 'Completed',
    patientList: [
      {
        address: 'Los Angeles No. 2 Lake Park',
        name: 'Jane Smith',
        age: '28y',
        gender: 'Female',
        dob: '15/05/1994',
        status: 'Completed',
        referredOn: '12/03/2021',
        program: 'Diabetes',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000019',
    status: 'Enrolled',
    patientList: [
      {
        address: 'Chicago No. 3 Lake Park',
        name: 'Michael Johnson',
        age: '45y',
        gender: 'Male',
        dob: '22/08/1977',
        status: 'Enrolled',
        referredOn: '19/07/2019',
        program: 'Cardiology',
      },
      {
        address: 'Chicago No. 4 Lake Park',
        name: 'Sarah Johnson',
        age: '40y',
        gender: 'Female',
        dob: '30/11/1982',
        status: 'Failed',
        referredOn: '05/11/2020',
        program: 'Oncology',
      },
    ],
    _expandNestedRow: false,
  },
  {
    id: 'C1000000020',
    status: 'Failed',
    patientList: [
      {
        address: 'Houston No. 4 Lake Park',
        name: 'Emily Davis',
        age: '35y',
        gender: 'Female',
        dob: '30/11/1987',
        status: 'Failed',
        referredOn: '05/11/2020',
        program: 'Oncology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000021',
    status: 'Completed',
    patientList: [
      {
        address: 'Phoenix No. 5 Lake Park',
        name: 'David Wilson',
        age: '50y',
        gender: 'Male',
        dob: '14/02/1972',
        status: 'Completed',
        referredOn: '23/06/2021',
        program: 'Neurology',
      },
      {
        address: 'Phoenix No. 6 Lake Park',
        name: 'Sophia Wilson',
        age: '29y',
        gender: 'Female',
        dob: '10/09/1993',
        status: 'Enrolled',
        referredOn: '17/01/2022',
        program: 'Gastroenterology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000022',
    status: 'Enrolled',
    patientList: [
      {
        address: 'Philadelphia No. 6 Lake Park',
        name: 'Sophia Martinez',
        age: '29y',
        gender: 'Female',
        dob: '10/09/1993',
        status: 'Enrolled',
        referredOn: '17/01/2022',
        program: 'Gastroenterology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000023',
    status: 'Failed',
    patientList: [
      {
        address: 'San Antonio No. 7 Lake Park',
        name: 'James Anderson',
        age: '40y',
        gender: 'Male',
        dob: '25/04/1982',
        status: 'Failed',
        referredOn: '30/04/2020',
        program: 'Pulmonology',
      },
      {
        address: 'San Antonio No. 8 Lake Park',
        name: 'Laura Anderson',
        age: '38y',
        gender: 'Female',
        dob: '14/02/1984',
        status: 'Completed',
        referredOn: '23/06/2021',
        program: 'Neurology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000024',
    status: 'Completed',
    patientList: [
      {
        address: 'San Diego No. 8 Lake Park',
        name: 'Olivia Thomas',
        age: '33y',
        gender: 'Female',
        dob: '05/12/1989',
        status: 'Completed',
        referredOn: '14/09/2021',
        program: 'Dermatology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000025',
    status: 'Enrolled',
    patientList: [
      {
        address: 'Dallas No. 9 Lake Park',
        name: 'Robert Jackson',
        age: '37y',
        gender: 'Male',
        dob: '18/07/1985',
        status: 'Enrolled',
        referredOn: '20/12/2019',
        program: 'Endocrinology',
      },
      {
        address: 'Dallas No. 10 Lake Park',
        name: 'Emma Jackson',
        age: '35y',
        gender: 'Female',
        dob: '08/03/1987',
        status: 'Failed',
        referredOn: '25/08/2020',
        program: 'Rheumatology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000026',
    status: 'Failed',
    patientList: [
      {
        address: 'San Jose No. 10 Lake Park',
        name: 'Isabella White',
        age: '26y',
        gender: 'Female',
        dob: '08/03/1996',
        status: 'Failed',
        referredOn: '25/08/2020',
        program: 'Rheumatology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000027',
    status: 'Completed',
    patientList: [
      {
        address: 'Austin No. 11 Lake Park',
        name: 'William Harris',
        age: '48y',
        gender: 'Male',
        dob: '12/10/1974',
        status: 'Completed',
        referredOn: '28/02/2021',
        program: 'Nephrology',
      },
      {
        address: 'Austin No. 12 Lake Park',
        name: 'Sophia Harris',
        age: '45y',
        gender: 'Female',
        dob: '21/06/1977',
        status: 'Enrolled',
        referredOn: '10/05/2022',
        program: 'Hematology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000028',
    status: 'Enrolled',
    patientList: [
      {
        address: 'Jacksonville No. 12 Lake Park',
        name: 'Mia Clark',
        age: '31y',
        gender: 'Female',
        dob: '21/06/1991',
        status: 'Enrolled',
        referredOn: '10/05/2022',
        program: 'Hematology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000029',
    status: 'Failed',
    patientList: [
      {
        address: 'Fort Worth No. 13 Lake Park',
        name: 'Charles Lewis',
        age: '42y',
        gender: 'Male',
        dob: '29/01/1980',
        status: 'Failed',
        referredOn: '15/03/2020',
        program: 'Urology',
      },
      {
        address: 'Fort Worth No. 14 Lake Park',
        name: 'Laura Lewis',
        age: '40y',
        gender: 'Female',
        dob: '03/08/1982',
        status: 'Completed',
        referredOn: '22/07/2021',
        program: 'Ophthalmology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000030',
    status: 'Completed',
    patientList: [
      {
        address: 'Columbus No. 14 Lake Park',
        name: 'Amelia Robinson',
        age: '27y',
        gender: 'Female',
        dob: '03/08/1995',
        status: 'Completed',
        referredOn: '22/07/2021',
        program: 'Ophthalmology',
      },
    ],
    _expandNestedRow: true,
  },
  {
    id: 'C1000000031',
    status: 'Enrolled',
    patientList: [
      {
        address: 'Charlotte No. 15 Lake Park',
        name: 'Henry Walker',
        age: '36y',
        gender: 'Male',
        dob: '27/05/1986',
        status: 'Enrolled',
        referredOn: '11/11/2019',
        program: 'Psychiatry',
      },
      {
        address: 'Charlotte No. 16 Lake Park',
        name: 'Emma Walker',
        age: '34y',
        gender: 'Female',
        dob: '15/09/1988',
        status: 'Failed',
        referredOn: '05/03/2020',
        program: 'Dermatology',
      },
    ],
    _expandNestedRow: true,
  },
];
