import React from 'react';
import { Avatar } from '@/index';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  'https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=37-592&m=dev',
  {
    imports: ["import { Avatar } from '@innovaccer/design-system'"],
    props: {
      appearance: figma.enum('Appearance', {
        Jal: 'jal',
        Stone: 'stone',
        Neem: 'neem',
        Haldi: 'haldi',
        Mirch: 'mirch',
        Tawak: 'tawak',
        Nimbu: 'nimbu',
        Neel: 'neel',
        Jamun: 'jamun',
      }),
      size: figma.enum('Size', {
        Regular: 'regular',
        Small: 'small',
      }),
      state: figma.enum('State', {
        Default: 'default',
        Focus: 'focus',
        Disabled: 'disabled',
      }),
      type: figma.enum('Type', {
        Image: 'image',
        Icon: 'icon',
        Text: 'text',
      }),
      shape: figma.enum('Shape', {
        Round: 'round',
        Square: 'square',
      }),
      fallback: figma.boolean('Fallback'),
    },
    example: (props) => <Avatar>hello</Avatar>,
  }
);
