import React from "react"
import { AvatarGroup } from "./AvatarGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AvatarGroup,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=37%3A593",
  {
    props: {
      size: figma.enum("Size", {
        Regular: "regular",
        Small: "small",
      }),
      count: figma.enum("Count", {
        "More than three": "more-than-three",
        "Less than three": "less-than-three",
      }),
      type: figma.enum("Type", {
        Initial: "initial",
        Icon: "icon",
        Image: "image",
      }),
    },
    example: (props) => <AvatarGroup />,
  },
)
