import React from "react"
import { Badge } from "./Badge"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=41%3A0",
  {
    props: {
      appearance: figma.enum("Appearance", {
        Jal: "jal",
        Stone: "stone",
        Neem: "neem",
        Haldi: "haldi",
        Mirch: "mirch",
        Tawak: "tawak",
        Nimbu: "nimbu",
        Neel: "neel",
        Jamun: "jamun",
      }),
      subtle: figma.boolean("Subtle"),
    },
    example: (props) => <Badge />,
  },
)
