import React from "react"
import { Box } from "./Box"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Box,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=44079%3A22596",
  {
    props: {
      size: figma.enum("Size", {
        Standard: "standard",
        Compressed: "compressed",
        Tight: "tight",
      }),
    },
    example: (props) => <Box />,
  },
)
