import React from "react"
import { Breadcrumbs } from "./Breadcrumbs"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Breadcrumbs,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=1056%3A68",
  {
    props: {
      overflow: figma.boolean("Overflow"),
    },
    example: (props) => <Breadcrumbs />,
  },
)
