import React from "react"
import { Calendar } from "./Calendar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Calendar,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=1308%3A5244",
  {
    props: {
      view: figma.enum("View", {
        Month: "month",
        Year: "year",
        Decade: "decade",
      }),
      size: figma.enum("Size", {
        Regular: "regular",
        Small: "small",
      }),
    },
    example: (props) => <Calendar />,
  },
)
