import React from "react"
import { Card } from "./Card"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Card,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=39%3A315",
  {
    props: {
      style: figma.enum("Style", {
        "Shadow 10": "shadow-10",
        "Shadow 20": "shadow-20",
        "Shadow 30": "shadow-30",
        "Shadow 40": "shadow-40",
        Subdued: "subdued",
        "No shadow": "no-shadow",
      }),
    },
    example: (props) => <Card />,
  },
)
