import React from "react"
import { Cell } from "./Cell"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Cell,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=75%3A1416",
  {
    props: {
      type: figma.enum("Type", {
        Title: "title",
        "Title + Avatar": "title---avatar",
        "Title + Image": "title---image",
        "Status Hint": "status-hint",
        Icon: "icon",
        Dropdown: "dropdown",
        Input: "input",
        "Date + Action": "date---action",
        "Date + Authors+ Action": "date---authors--action",
        "Collapsed Item": "collapsed-item",
        "Expanded Item": "expanded-item",
        "Reorder Item": "reorder-item",
        "Empty cell": "empty-cell",
      }),
      alignment: figma.enum("Alignment", {
        Left: "left",
        Center: "center",
        Right: "right",
      }),
      metadata: figma.boolean("Meta data"),
      checkbox: figma.boolean("Checkbox"),
      empty: figma.boolean("Empty"),
    },
    example: (props) => <Cell />,
  },
)
