import React from "react"
import { CheckboxIcon } from "./CheckboxIcon"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CheckboxIcon,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=85%3A483",
  {
    props: {
      size: figma.enum("Size", {
        Regular: "regular",
        Small: "small",
      }),
      type: figma.enum("Type", {
        Checked: "checked",
        Unchecked: "unchecked",
        Indeterminate: "indeterminate",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Active: "active",
        Focus: "focus",
        Disabled: "disabled",
      }),
      error: figma.boolean("Error"),
    },
    example: (props) => <CheckboxIcon />,
  },
)
