import React from "react"
import { Checkbox } from "./Checkbox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=95%3A33",
  {
    props: {
      size: figma.enum("Size", {
        Regular: "regular",
        Small: "small",
      }),
      type: figma.enum("Type", {
        Checked: "checked",
        Unchecked: "unchecked",
        Indeterminate: "indeterminate",
      }),
      helpText: figma.boolean("Help Text"),
      disabled: figma.boolean("Disabled"),
      error: figma.boolean("Error"),
    },
    example: (props) => <Checkbox />,
  },
)
