import React from "react"
import { Combobox } from "./Combobox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Combobox,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=14373%3A48206",
  {
    props: {
      inputsize: figma.enum("Input size", {
        Regular: "regular",
        Small: "small",
        Large: "large",
      }),
      optionItems: figma.boolean("Option Items"),
    },
    example: (props) => <Combobox />,
  },
)
