import React from "react"
import { Editable } from "./Editable"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Editable,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=800%3A2233",
  {
    props: {
      type: figma.enum("Type", {
        "Regular Text Input": "regular-text-input",
        "Small Text Input": "small-text-input",
        "Input with Chips": "input-with-chips",
        Dropdown: "dropdown",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Edit: "edit",
        "Error - Focus": "error---focus",
      }),
    },
    example: (props) => <Editable />,
  },
)
