import React from "react"
import { HorizontalNav } from "./HorizontalNav"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  HorizontalNav,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=86%3A724",
  {
    props: {
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Active: "active",
        Disabled: "disabled",
        Focus: "focus",
      }),
      variant: figma.enum("Variant", {
        Default: "default",
        "With icon": "with-icon",
        "With count": "with-count",
      }),
      activated: figma.boolean("Activated"),
    },
    example: (props) => <HorizontalNav />,
  },
)
