import React from "react"
import { Input } from "./Input"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Input,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=8%3A1197",
  {
    props: {
      size: figma.enum("Size", {
        Regular: "regular",
        Small: "small",
        Large: "large",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Focus: "focus",
        "Error - Focus": "error---focus",
        "Read only": "read-only",
        Disabled: "disabled",
      }),
      lefticon: figma.boolean("Left icon"),
      placeholder: figma.boolean("Placeholder"),
    },
    example: (props) => <Input />,
  },
)
