import React from "react"
import { Menu } from "./Menu"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Menu,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=1481%3A10464",
  {
    props: {
      size: figma.enum("Size", {
        Regular: "regular",
        Small: "small",
      }),
      popoverposition: figma.enum("Popover position", {
        Bottom: "bottom",
        Top: "top",
      }),
      triggeralignment: figma.enum("Trigger alignment", {
        Right: "right",
        Left: "left",
      }),
    },
    example: (props) => <Menu />,
  },
)
