import React from "react"
import { ProgressBar } from "./ProgressBar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ProgressBar,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=441%3A1443",
  {
    props: {
      size: figma.enum("Size", {
        Regular: "regular",
        Small: "small",
      }),
      percentage: figma.enum("Percentage", {
        "10%": "10-",
        "20%": "20-",
        "30%": "30-",
        "40%": "40-",
        "50%": "50-",
        "60%": "60-",
        "70%": "70-",
        "80%": "80-",
        "90%": "90-",
        "100%": "100-",
      }),
    },
    example: (props) => <ProgressBar />,
  },
)
