import React from "react"
import { SearchInput } from "./SearchInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SearchInput,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=6446%3A31167",
  {
    props: {
      state: figma.enum("State", {
        Default: "default",
        Focus: "focus",
      }),
      placeholder: figma.boolean("Placeholder"),
    },
    example: (props) => <SearchInput />,
  },
)
