import React from "react"
import { Spinner } from "./Spinner"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Spinner,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=47585%3A80",
  {
    props: {
      property: figma.enum("Property 1", {
        Default: "default",
        Variant2: "variant2",
        Variant3: "variant3",
        Variant4: "variant4",
      }),
    },
    example: (props) => <Spinner />,
  },
)
