import React from "react"
import { Tab } from "./Tab"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Tab,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=34610%3A1253",
  {
    props: {
      variant: figma.enum("Variant", {
        Basic: "basic",
        "With count": "with-count",
        "With icon": "with-icon",
      }),
      activated: figma.boolean("Activated"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Active: "active",
        Focus: "focus",
        Disabled: "disabled",
        Dragged: "dragged",
      }),
      dismissible: figma.boolean("Dismissible"),
    },
    example: (props) => <Tab />,
  },
)
