import React from "react"
import { Toast } from "./Toast"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Toast,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=694%3A632",
  {
    props: {
      autodismiss: figma.boolean("Auto dismiss"),
      appearance: figma.enum("Appearance", {
        Info: "info",
        Success: "success",
        Warning: "warning",
        Alert: "alert",
      }),
      description: figma.boolean("Description"),
      actions: figma.boolean("Actions"),
    },
    example: (props) => <Toast />,
  },
)
