import React from "react"
import { VerificationCodeInput } from "./VerificationCodeInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  VerificationCodeInput,
  "https://www.figma.com/design/w8sqBtJpvq86D06UE7gN0T/branch/0LPEpuAwooHbyZ1UgPWZfq/MDS---Web?node-id=1229%3A2831",
  {
    props: {
      noofdigits: figma.enum("No. of digits", {
        "4": "4",
        "6": "6",
      }),
    },
    example: (props) => <VerificationCodeInput />,
  },
)
