export const tokenColors = [
    [
      { token: "--primary", value: "#0070DD" },
      { token: "--primary-dark", value: "#00509F" },
      { token: "--primary-darker", value: "#003365" },
      { token: "--primary-light", value: "#4F9DE7" },
      { token: "--primary-lighter", value: "#97C5F0" },
      { token: "--primary-lightest", value: "#DCECF9" },
    ],
    [
      { token: "--alert", value: "#D93737" },
      { token: "--alert-dark", value: "#9C2828" },
      { token: "--alert-darker", value: "#631919" },
      { token: "--alert-light", value: "#EB776C" },
      { token: "--alert-lighter", value: "#F7ADA5" },
      { token: "--alert-lightest", value: "#F9E2E2" },
    ],
    [
      { token: "--success", value: "#2EA843" },
      { token: "--success-dark", value: "#227934" },
      { token: "--success-darker", value: "#154D26" },
      { token: "--success-light", value: "#71C077" },
      { token: "--success-lighter", value: "#A5D8AA" },
      { token: "--success-lightest", value: "#D7EFDF" },
    ],
    [
      { token: "--warning", value: "#FFC208" },
      { token: "--warning-dark", value: "#B78707" },
      { token: "--warning-darker", value: "#6B4A06" },
      { token: "--warning-light", value: "#FFD462" },
      { token: "--warning-lighter", value: "#FFE597" },
      { token: "--warning-lightest", value: "#FFF5C7" },
    ],
    [
      { token: "--inverse", value: "#2F2F2F" },
      { token: "--inverse-light", value: "#595959" },
      { token: "--inverse-lighter", value: "#868686" },
      { token: "--inverse-lightest", value: "#A6A6A6" },
      { token: "--secondary", value: "#D5D5D5" },
      { token: "--secondary-dark", value: "#C5C5C5" },
      { token: "--secondary-light", value: "#E5E5E5" },
      { token: "--secondary-lighter", value: "#ECECEC" },
      { token: "--secondary-lightest", value: "#F4F4F4" },
    ],
    [
      { token: "--accent1", value: "#F07D00" },
      { token: "--accent1-dark", value: "#B35F13" },
      { token: "--accent1-darker", value: "#743208" },
      { token: "--accent1-light", value: "#FEAC5F" },
      { token: "--accent1-lighter", value: "#FFC998" },
      { token: "--accent1-lightest", value: "#FDE6CE" },
    ],
    [
      { token: "--accent2", value: "#7A53B2" },
      { token: "--accent2-dark", value: "#644491" },
      { token: "--accent2-darker", value: "#4E3572" },
      { token: "--accent2-light", value: "#9D7EC6" },
      { token: "--accent2-lighter", value: "#BFAADA" },
      { token: "--accent2-lightest", value: "#E0D8EE" },
    ],
    [
      { token: "--accent3", value: "#3D51D4" },
      { token: "--accent3-dark", value: "#2C3A98" },
      { token: "--accent3-darker", value: "#1C2561" },
      { token: "--accent3-light", value: "#7583E1" },
      { token: "--accent3-lighter", value: "#ABB4ED" },
      { token: "--accent3-lightest", value: "#E2E5F9" },
    ],
    [
      { token: "--accent4", value: "#82C91E" },
      { token: "--accent4-dark", value: "#578715" },
      { token: "--accent4-darker", value: "#304A0B" },
      { token: "--accent4-light", value: "#A6D763" },
      { token: "--accent4-lighter", value: "#C6E599" },
      { token: "--accent4-lightest", value: "#E3F3CE" },
    ],
  ];
  
export const spacingData = [
    { token: "--spacing-xs", value: "1px" },
    { token: "--spacing-s", value: "2px" },
    { token: "--spacing-m", value: "4px" },
    { token: "--spacing", value: "8px" },
    { token: "--spacing-l", value: "12px" },
    { token: "--spacing-2", value: "16px" },
    { token: "--spacing-xl", value: "24px" },
    { token: "--spacing-3", value: "32px" },
    { token: "--spacing-4", value: "48px" },
    { token: "--spacing-5", value: "64px" },
    { token: "--spacing-6", value: "96px" },
    { token: "--spacing-7", value: "128px" },
    { token: "--spacing-8", value: "176px" },
    { token: "--spacing-9", value: "256px" },
];  