export interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  role: string;
  status: string;
}

export const mockUsersData: User[] = [
  { id: '1', firstName: 'John', lastName: 'Doe', email: 'john.doe@example.com', role: 'Admin', status: 'Active' },
  { id: '2', firstName: 'Jane', lastName: 'Smith', email: 'jane.smith@example.com', role: 'User', status: 'Active' },
  {
    id: '3',
    firstName: 'Bob',
    lastName: 'Johnson',
    email: 'bob.johnson@example.com',
    role: 'User',
    status: 'Inactive',
  },
  {
    id: '4',
    firstName: 'Alice',
    lastName: 'Williams',
    email: 'alice.williams@example.com',
    role: 'Admin',
    status: 'Active',
  },
  {
    id: '5',
    firstName: 'Charlie',
    lastName: 'Brown',
    email: 'charlie.brown@example.com',
    role: 'User',
    status: 'Active',
  },
  {
    id: '6',
    firstName: 'Diana',
    lastName: 'Davis',
    email: 'diana.davis@example.com',
    role: 'User',
    status: 'Inactive',
  },
  {
    id: '7',
    firstName: 'Edward',
    lastName: 'Miller',
    email: 'edward.miller@example.com',
    role: 'Admin',
    status: 'Active',
  },
  {
    id: '8',
    firstName: 'Fiona',
    lastName: 'Wilson',
    email: 'fiona.wilson@example.com',
    role: 'User',
    status: 'Active',
  },
  {
    id: '9',
    firstName: 'George',
    lastName: 'Moore',
    email: 'george.moore@example.com',
    role: 'User',
    status: 'Active',
  },
  {
    id: '10',
    firstName: 'Helen',
    lastName: 'Taylor',
    email: 'helen.taylor@example.com',
    role: 'Admin',
    status: 'Inactive',
  },
  {
    id: '11',
    firstName: 'Ian',
    lastName: 'Anderson',
    email: 'ian.anderson@example.com',
    role: 'User',
    status: 'Active',
  },
  {
    id: '12',
    firstName: 'Julia',
    lastName: 'Thomas',
    email: 'julia.thomas@example.com',
    role: 'User',
    status: 'Active',
  },
  {
    id: '13',
    firstName: 'Kevin',
    lastName: 'Jackson',
    email: 'kevin.jackson@example.com',
    role: 'Admin',
    status: 'Active',
  },
  {
    id: '14',
    firstName: 'Laura',
    lastName: 'White',
    email: 'laura.white@example.com',
    role: 'User',
    status: 'Inactive',
  },
  {
    id: '15',
    firstName: 'Michael',
    lastName: 'Harris',
    email: 'michael.harris@example.com',
    role: 'User',
    status: 'Active',
  },
  {
    id: '16',
    firstName: 'Nancy',
    lastName: 'Martin',
    email: 'nancy.martin@example.com',
    role: 'Admin',
    status: 'Active',
  },
  {
    id: '17',
    firstName: 'Oliver',
    lastName: 'Thompson',
    email: 'oliver.thompson@example.com',
    role: 'User',
    status: 'Active',
  },
  {
    id: '18',
    firstName: 'Patricia',
    lastName: 'Garcia',
    email: 'patricia.garcia@example.com',
    role: 'User',
    status: 'Inactive',
  },
  {
    id: '19',
    firstName: 'Quinn',
    lastName: 'Martinez',
    email: 'quinn.martinez@example.com',
    role: 'Admin',
    status: 'Active',
  },
  {
    id: '20',
    firstName: 'Rachel',
    lastName: 'Robinson',
    email: 'rachel.robinson@example.com',
    role: 'User',
    status: 'Active',
  },
  {
    id: '21',
    firstName: 'Samuel',
    lastName: 'Clark',
    email: 'samuel.clark@example.com',
    role: 'User',
    status: 'Active',
  },
  {
    id: '22',
    firstName: 'Tina',
    lastName: 'Rodriguez',
    email: 'tina.rodriguez@example.com',
    role: 'Admin',
    status: 'Inactive',
  },
  {
    id: '23',
    firstName: 'Victor',
    lastName: 'Lewis',
    email: 'victor.lewis@example.com',
    role: 'User',
    status: 'Active',
  },
  { id: '24', firstName: 'Wendy', lastName: 'Lee', email: 'wendy.lee@example.com', role: 'User', status: 'Active' },
  {
    id: '25',
    firstName: 'Xavier',
    lastName: 'Walker',
    email: 'xavier.walker@example.com',
    role: 'Admin',
    status: 'Active',
  },
];
